### ISSUE TITLE
Question, does the server also work in the browser?

### ISSUE THREAD

**Issue by ryanwild** [dominictarr/pull-diff#1]
I'm thinking of using this to set up two channels for IO between server/browser...

**Comment by dominictarr** [comment]
there is no server in this module, this is just a stream, 

you could do it like this:

``` js
var ws = require('pull-ws').connect(websocket_url) //pseudocode
var JSONDL = require('pull-json-doubleline')
var write_obv = Obv()
var read_obv = Obv()

//the source 
pull(
  Diff(write_obv)()
  JSONDL.stringify(),
  ws.sink()
)

pull(
  ws.source,
  JSONDL.parse(),
  Diff.sink(read_obv)
)
```

note, the client can only modify `write_obv` but can read `read_obv` (which the server writes to)

you might also be interested in: https://github.com/dominictarr/scuttlebutt

**Comment by ryanwild** [comment]
awesome thanks :+1:
